import type { ModelRecord } from "./model-config";

/**
 * dsh（DeepSeek Harness）provider 配置桥接。
 *
 * 把 cc_start 的模型配置（~/.claude/models/*.json，ANTHROPIC_* env 形状）
 * 转换为 dsh 的 provider 配置层（llm-pi-ai.providers），供 `cc dsh` 启动时
 * 通过 `dsh --patch <file>` 注入。
 *
 * 原则：
 * - cc_start 是唯一配置源，本文件只做纯函数转换（无 IO，便于单测）
 * - 凭据不落盘：只写 apiKeyEnv 引用，key 由启动器导出到环境变量后由 dsh 解析
 * - 剥掉 Claude Code 专属的 [1m] 等上下文后缀（dsh 不需要）
 */

/** 同一端点（baseURL + 凭据 env）共享一个 provider 的模型组。 */
export interface DshProviderGroup {
  id: string;
  baseURL: string;
  apiKeyEnv: string;
  models: string[];
  aliases: string[];
}

/** 模型 ID 去 [1m]/[128k] 等上下文后缀（Claude Code 标记，dsh 不需要）。 */
export function stripContextSuffix(modelId: string): string {
  return modelId.replace(/\[[0-9]+[kKmM]\]$/, "").trim();
}

/** provider id：dsh 要求 lowercase Provider ID（小写字母数字连字符）。 */
export function slugifyProviderId(alias: string): string {
  const slug = alias
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return slug || "provider";
}

/**
 * provider 专属的凭据环境变量名。
 * 每个 provider 必须用独立变量，否则 UI 里切换模型时会拿错 key
 * （所有 provider 共享同一变量 = 全部使用启动时那个模型的 key）。
 */
export function credentialEnvFor(providerId: string): string {
  return `CC_START_KEY_${providerId.toUpperCase().replace(/-/g, "_")}`;
}

/**
 * DeepSeek 模型是否声明推理级别。
 *
 * 按模型 id（含 deepseek）判断，覆盖全部渠道：官方 api.deepseek.com、
 * 火山方舟、本地代理等——已实测这些 anthropic 兼容端点全部支持
 * adaptive thinking（`thinking:{type:"adaptive"}` + `output_config.effort`）。
 *
 * 参考 models.dev/api.json：各供应商（DeepSeek 官方/硅基流动/NVIDIA 等）
 * 的 effort 值都是 Anthropic 标准名（low/medium/high/max），无特殊 wire
 * 格式差异，差异仅在支持集合（如官方 v4-flash 标注 low/high/max、
 * v4-pro 标注 high/max）；本桥接统一声明完整集合（实测端点对未标注的
 * medium 同样接受）。硅基流动等未标注 effort 的渠道未实测，若后续请求
 * 被拒可在此按 baseURL 裁剪级别集合。
 *
 * 其他模型（GLM/Qwen/Kimi 等）未经验证，不声明以免请求被拒。
 */
export function supportsDeepSeekReasoning(modelId: string): boolean {
  return stripContextSuffix(modelId).toLowerCase().includes("deepseek");
}

/** DeepSeek anthropic 端点可用的推理级别（wire 值即 effort 值）。 */
export const DEEPSEEK_REASONING_EFFORTS: ReadonlyArray<readonly [string, string]> = [
  ["off", "null"],
  ["low", "low"],
  ["medium", "medium"],
  ["high", "high"],
  ["max", "max"],
];

/** YAML 双引号字符串转义（js-yaml 兼容）。 */
export function yamlString(value: string): string {
  return '"' + value.replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';
}

/**
 * 按 baseURL + 凭据 env 把模型记录分组。
 * 同一端点（如多个 DeepSeek 模型）合并为一个 provider 的 models 列表，
 * 与 dsh 的 Settings → Models 显示方式一致。
 */
export function groupModelsByEndpoint(models: ModelRecord[]): DshProviderGroup[] {
  const byKey = new Map<string, DshProviderGroup>();
  const usedIds = new Set<string>();

  for (const record of models) {
    const env = record.settings.env;
    const baseURL = env.ANTHROPIC_BASE_URL;
    const modelId = env.ANTHROPIC_MODEL;
    if (!baseURL || !modelId) {
      continue; // REQUIRED_ENV_KEYS 已保证，防御性跳过
    }

    // 按端点分组：同 baseURL 的模型共享一个 provider（共享凭据）
    const key = baseURL;
    let group = byKey.get(key);
    if (!group) {
      // provider id 需唯一（避免两个 alias 生成相同 slug 导致凭据变量冲突）
      const baseId = slugifyProviderId(record.alias);
      let id = baseId;
      let suffix = 2;
      while (usedIds.has(id)) {
        id = baseId + '-' + suffix++;
      }
      usedIds.add(id);
      group = {
        id,
        baseURL,
        apiKeyEnv: credentialEnvFor(id),
        models: [],
        aliases: [],
      };
      byKey.set(key, group);
    }

    const stripped = stripContextSuffix(modelId);
    if (!group.models.includes(stripped)) {
      group.models.push(stripped);
    }
    group.aliases.push(record.alias);
  }

  // 稳定顺序：按 baseURL 排序，同端点内按模型名排序
  const groups = [...byKey.values()].sort((a, b) => a.baseURL.localeCompare(b.baseURL));
  for (const group of groups) {
    group.models.sort((a, b) => a.localeCompare(b));
    group.aliases.sort((a, b) => a.localeCompare(b));
  }
  return groups;
}

/**
 * 构建启动时需要的凭据环境映射（env 变量名 → key 值）。
 * 每个 provider 组取组内任一模型的 key（同端点共享凭据），
 * 供 cc dsh 启动时导出——这样 UI 里切换任意模型都有正确的 key。
 */
export function buildCredentialEnv(models: ModelRecord[]): Record<string, string> {
  const result: Record<string, string> = {};
  for (const group of groupModelsByEndpoint(models)) {
    const aliasOf = (a: string): ModelRecord | undefined =>
      models.find((m) => m.alias === a);
    const token = group.aliases
      .map((a) => aliasOf(a)?.settings.env.ANTHROPIC_AUTH_TOKEN)
      .find((t): t is string => typeof t === 'string' && t.length > 0);
    if (token) {
      result[group.apiKeyEnv] = token;
    }
  }
  return result;
}

export function buildDshProvidersYaml(models: ModelRecord[]): string {
  const groups = groupModelsByEndpoint(models);
  if (groups.length === 0) {
    return "";
  }

  const lines: string[] = [
    "# Generated by cc-start (`cc dsh`). Providers mirror ~/.claude/models/*.json.",
    "# Credentials resolve via apiKeyEnv from the environment at launch; no key is stored here.",
    "- id: llm-pi-ai",
    "  config:",
    "    providers:",
  ];
  for (const group of groups) {
    lines.push(
      `      ${group.id}:`,
      "        api: anthropic-messages",
      `        baseURL: ${yamlString(group.baseURL)}`,
      `        apiKeyEnv: ${group.apiKeyEnv}`,
      "        models:"
    );
    for (const modelId of group.models) {
      lines.push(`          - id: ${yamlString(modelId)}`);
      // DeepSeek 模型（任意渠道，官方/火山方舟/代理均已实测支持）：
      // 声明推理级别，composer 模型选择器显示推理程度选项
      if (supportsDeepSeekReasoning(modelId)) {
        lines.push("            reasoningEfforts:");
        for (const [level, wire] of DEEPSEEK_REASONING_EFFORTS) {
          lines.push(
            wire === "null"
              ? `              ${level}: null`
              : `              ${level}: ${yamlString(wire)}`
          );
        }
      }
    }
  }
  return lines.join("\n") + "\n";
}
